---
- name: Make sure gpg-agent is installed
  ansible.builtin.apt:
    name: gpg-agent
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Make sure Plex apt key is added
  ansible.builtin.apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present

- name: Make sure Plex repository is added
  ansible.builtin.apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present
    update_cache: true
    filename: plexmediaserver

- name: Make sure plexmediaserver is installed
  ansible.builtin.apt:
    name: plexmediaserver
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Make sure Plex is running
  ansible.builtin.systemd:
    name: plexmediaserver
    state: started
    enabled: true
    daemon_reload: true
